/*
 * Copyright (c) 2015, Andrey Lavrov <lavroff@gmail.com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
package cy.alavrov.jminerguide.forms;

/**
 *
 * @author Andrey Lavrov <lavroff@gmail.com>
 */
public class JAsteroidFilterDialog extends javax.swing.JDialog {

    /**
     * Creates new form JAsteroidFilterDialog
     */
    public JAsteroidFilterDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jCheckBoxVeldspar = new javax.swing.JCheckBox();
        jCheckBoxScordite = new javax.swing.JCheckBox();
        jCheckBoxPyroxeres = new javax.swing.JCheckBox();
        jCheckBoxPlagioclase = new javax.swing.JCheckBox();
        jCheckBoxOmber = new javax.swing.JCheckBox();
        jCheckBoxKernite = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jCheckBoxJaspet = new javax.swing.JCheckBox();
        jCheckBoxHemorphite = new javax.swing.JCheckBox();
        jCheckBoxHedbergite = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jCheckBoxGneiss = new javax.swing.JCheckBox();
        jCheckBoxDarkOchre = new javax.swing.JCheckBox();
        jCheckBoxCrokite = new javax.swing.JCheckBox();
        jCheckBoxSpodumain = new javax.swing.JCheckBox();
        jCheckBoxBistot = new javax.swing.JCheckBox();
        jCheckBoxArkonor = new javax.swing.JCheckBox();
        jCheckBoxMercoxit = new javax.swing.JCheckBox();
        jButtonClose = new javax.swing.JButton();
        jButtonAll = new javax.swing.JButton();
        jButtonNone = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select Ores");

        jLabel1.setText("HiSec Ores");

        jPanel1.setToolTipText("");
        jPanel1.setLayout(new java.awt.GridLayout(2, 3));

        jCheckBoxVeldspar.setText("Veldspar");
        jPanel1.add(jCheckBoxVeldspar);

        jCheckBoxScordite.setText("Scordite");
        jPanel1.add(jCheckBoxScordite);

        jCheckBoxPyroxeres.setText("Pyroxeres");
        jPanel1.add(jCheckBoxPyroxeres);

        jCheckBoxPlagioclase.setText("Plagioclase");
        jPanel1.add(jCheckBoxPlagioclase);

        jCheckBoxOmber.setText("Omber");
        jPanel1.add(jCheckBoxOmber);

        jCheckBoxKernite.setText("Kernite");
        jPanel1.add(jCheckBoxKernite);

        jLabel2.setText("LowSec Ores");

        jPanel2.setLayout(new java.awt.GridLayout(1, 3));

        jCheckBoxJaspet.setText("Jaspet");
        jPanel2.add(jCheckBoxJaspet);

        jCheckBoxHemorphite.setText("Hemorphite");
        jPanel2.add(jCheckBoxHemorphite);

        jCheckBoxHedbergite.setText("Hedbergite");
        jPanel2.add(jCheckBoxHedbergite);

        jLabel3.setText("NullSec Ores");

        jPanel3.setLayout(new java.awt.GridLayout(3, 3));

        jCheckBoxGneiss.setText("Gneiss");
        jPanel3.add(jCheckBoxGneiss);

        jCheckBoxDarkOchre.setText("Dark Ochre");
        jPanel3.add(jCheckBoxDarkOchre);

        jCheckBoxCrokite.setText("Crokite");
        jPanel3.add(jCheckBoxCrokite);

        jCheckBoxSpodumain.setText("Spodumain");
        jPanel3.add(jCheckBoxSpodumain);

        jCheckBoxBistot.setText("Bistot");
        jPanel3.add(jCheckBoxBistot);

        jCheckBoxArkonor.setText("Arkonor");
        jPanel3.add(jCheckBoxArkonor);

        jCheckBoxMercoxit.setText("Mercoxit");
        jPanel3.add(jCheckBoxMercoxit);

        jButtonClose.setText("Close");

        jButtonAll.setText("All");

        jButtonNone.setText("None");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonClose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonNone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAll)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClose)
                    .addComponent(jButtonAll)
                    .addComponent(jButtonNone))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JAsteroidFilterDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JAsteroidFilterDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JAsteroidFilterDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JAsteroidFilterDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JAsteroidFilterDialog dialog = new JAsteroidFilterDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAll;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonNone;
    private javax.swing.JCheckBox jCheckBoxArkonor;
    private javax.swing.JCheckBox jCheckBoxBistot;
    private javax.swing.JCheckBox jCheckBoxCrokite;
    private javax.swing.JCheckBox jCheckBoxDarkOchre;
    private javax.swing.JCheckBox jCheckBoxGneiss;
    private javax.swing.JCheckBox jCheckBoxHedbergite;
    private javax.swing.JCheckBox jCheckBoxHemorphite;
    private javax.swing.JCheckBox jCheckBoxJaspet;
    private javax.swing.JCheckBox jCheckBoxKernite;
    private javax.swing.JCheckBox jCheckBoxMercoxit;
    private javax.swing.JCheckBox jCheckBoxOmber;
    private javax.swing.JCheckBox jCheckBoxPlagioclase;
    private javax.swing.JCheckBox jCheckBoxPyroxeres;
    private javax.swing.JCheckBox jCheckBoxScordite;
    private javax.swing.JCheckBox jCheckBoxSpodumain;
    private javax.swing.JCheckBox jCheckBoxVeldspar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
